### ISSUE TITLE
Case insensitivity for commands

### ISSUE THREAD

**Issue by CaptainWilder** [TwitchIO/TwitchIO#95] opened 2020-03-08 21:25 UTC
Requesting commands to be case insensitive, or have support for .casefold().

**Comment by ParkEunBlank** [comment] 2020-04-30 06:53
you can get around this by doing something like this
`    async def event_message(self, message):
        ctx = await bot.get_context(message=message)
        if str(message.content).lower().startswith("!tester"):
            await self.testercommand(ctx)`

**Comment by BairdMcI** [comment] 2021-02-04 00:41
Bump for TIO v2 :)

**Comment by IAmTomahawkx** [comment] 2021-02-08 01:25
turns out this is already complete on 2.0, and apparently a duplicate of #78 . I probably shouldve paid closer attention earlier

**Closed by IAmTomahawkx** 2021-02-08 01:25 UTC
Labels: new feature

**Comment by Houdini111** [comment] 2023-01-04 17:12
I can't find anything in the documentation, nor in any PRs, nor in the code about this. How do you enable case insensitive commands?

**Comment by chillymosh** [comment] 2023-01-04 17:14
@Houdini111 for questions like these it is best to join the discord support server and ask, or use the Github Discussions
```
class TwitchChatBot(commands.Bot):
    def __init__(self):
        super().__init__(
            token="",
            client_secret=config["CLIENT_SECRET"],
            prefix="!",
            initial_channels=["ch1", "ch2"],
            case_insensitive=True,
        )
```
